fix: update Docker environment for CraftCMS 3.9.15 compatibility
- Migrate base image from ubuntu:bionic (PHP 7.2) to ubuntu:jammy
  (PHP 8.1)
- Update PHP packages to php8.1 and extensions
- Add mysql-client package for mysqldump support
- Update composer installation to use dynamic checksum verification
- Add composer update block in Dockerfile to install correct vendor
  dependencies
- Remove path repository before composer update to avoid build-time path
  errors
- Fix CraftCMS version in composer.json from ^3.6.4 to 3.9.15
- Update platform PHP version in composer.json from 7.2.5 to 8.1.0
- Remove outdated composer.lock to force regeneration during build
- Remove licenseKeyStatus column from database seed (dropped in
  CraftCMS 3.9.x)
- Add --ignore-platform-reqs to composer require in install.sh for
  plugin compatibility
- Add netlogo web-application volume mount in docker-compose.yml
- Move CMD directive to end of Dockerfile

diff --git a/docker/build/server/ubuntu/Dockerfile b/docker/build/server/ubuntu/Dockerfile
--- a/docker/build/server/ubuntu/Dockerfile
+++ b/docker/build/server/ubuntu/Dockerfile
@@ -1,29 +1,34 @@
-FROM ubuntu:bionic
-
-# Surpresses debconf complaints of trying to install apt packages interactively
-# https://github.com/moby/moby/issues/4032#issuecomment-192327844
+FROM ubuntu:jammy
 
 ARG DEBIAN_FRONTEND=noninteractive
 
 RUN apt update --fix-missing
 RUN apt upgrade -y
-RUN apt install nano less unzip zip curl apache2 mysql-server composer ufw less wget php libapache2-mod-php php-mysql php-curl php-xml php-zip php-mbstring php-soap php-imagick php-intl -y 
+RUN apt install -y nano less unzip zip curl apache2 ufw wget mysql-client \
+    php8.1 libapache2-mod-php8.1 php8.1-mysql php8.1-curl php8.1-xml \
+    php8.1-zip php8.1-mbstring php8.1-soap php8.1-imagick php8.1-intl \
+    php8.1-gd php8.1-bcmath
 RUN ufw allow in "Apache"
-RUN service apache2 restart
-RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
-RUN php composer-setup.php
-RUN php -r "unlink('composer-setup.php');"
-
+RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
+    && EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')" \
+    && ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" \
+    && if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then echo 'ERROR: Invalid installer checksum'; rm composer-setup.php; exit 1; fi \
+    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
+    && rm composer-setup.php
 WORKDIR /var/www
 COPY ["craftcms-source", "craftcms"]
 RUN chown -R www-data:www-data craftcms
-
-CMD ["apachectl","-D","FOREGROUND"]
+RUN cd /var/www/craftcms \
+    && composer config audit.block-insecure false \
+    && composer config allow-plugins.yiisoft/yii2-composer true \
+    && composer config allow-plugins.craftcms/plugin-installer true \
+    && cp composer.json composer.json.bak \
+    && php -r "\$c=json_decode(file_get_contents('composer.json'),true); unset(\$c['repositories']); file_put_contents('composer.json',json_encode(\$c,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));" \
+    && composer update --no-interaction --ignore-platform-reqs \
+    && mv composer.json.bak composer.json
 RUN a2enmod rewrite
 RUN a2enmod headers
 RUN a2enmod ssl
-
 EXPOSE 80
 EXPOSE 443
-
+CMD ["apachectl","-D","FOREGROUND"]
